minimumReleaseAge: 10080
saveExact: true
engineStrict: true
preferFrozenLockfile: true
verifyDepsBeforeRun: false

allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false
  '@swc/core': false
  unrs-resolver: false
